/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContentItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contentType' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'partnerId' : IDL.Nat,
  'priceE8s' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlatformRevenue = IDL.Record({
  'partnerCount' : IDL.Nat,
  'totalCreatorShare' : IDL.Nat,
  'totalHyveilShare' : IDL.Nat,
  'totalPurchases' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const PartnerStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const PartnerRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PartnerStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'monetizationModel' : IDL.Text,
  'chains' : IDL.Vec(IDL.Text),
  'totalRevenue' : IDL.Nat,
  'registeredAt' : IDL.Int,
  'canisterId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChannelRevenue = IDL.Record({
  'partnerName' : IDL.Text,
  'creatorShare' : IDL.Nat,
  'hyveilShare' : IDL.Nat,
  'partnerId' : IDL.Nat,
  'purchaseCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'canisterId' : IDL.Principal,
});
export const RevenueStats = IDL.Record({
  'creatorShare' : IDL.Nat,
  'hyveilShare' : IDL.Nat,
  'purchaseCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const Comment = IDL.Record({
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
});
export const VideoMeta = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likes' : IDL.Nat,
  'caption' : IDL.Text,
  'blobId' : IDL.Text,
  'comments' : IDL.Vec(Comment),
  'uploadedAt' : IDL.Nat,
});
export const ProxyResponse = IDL.Record({
  'body' : IDL.Text,
  'statusCode' : IDL.Nat,
  'success' : IDL.Bool,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'contentId' : IDL.Text,
  'hyveilShareE8s' : IDL.Nat,
  'partnerId' : IDL.Nat,
  'totalAmountE8s' : IDL.Nat,
  'creatorShareE8s' : IDL.Nat,
  'timestamp' : IDL.Int,
  'buyer' : IDL.Principal,
});
export const RegisterPartnerInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'chains' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addContentItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [ContentItem],
      [],
    ),
  'approvePartner' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimOwnerIfFirst' : IDL.Func([], [IDL.Bool], []),
  'clearChannelWasm' : IDL.Func([], [], []),
  'depositIcp' : IDL.Func([IDL.Nat], [], []),
  'getAllPartnersRevenue' : IDL.Func([], [PlatformRevenue], ['query']),
  'getApprovedPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelWasmStatus' : IDL.Func(
      [],
      [IDL.Record({ 'size' : IDL.Nat, 'loaded' : IDL.Bool })],
      ['query'],
    ),
  'getContentItems' : IDL.Func([IDL.Nat], [IDL.Vec(ContentItem)], ['query']),
  'getHyvBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getHyveilCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getHyveilPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getMyChannelsRevenue' : IDL.Func([], [IDL.Vec(ChannelRevenue)], ['query']),
  'getMyIcpBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
  'getOraclePrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getPartnerRevenue' : IDL.Func([IDL.Nat], [RevenueStats], ['query']),
  'getPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
  'getRegistrationFee' : IDL.Func([], [IDL.Nat], ['query']),
  'getTokenCanisterId' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'proxyFetch' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))),
      ],
      [ProxyResponse],
      [],
    ),
  'purchaseContent' : IDL.Func([IDL.Text], [PurchaseRecord], []),
  'registerChannelForMining' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'registerPartner' : IDL.Func([RegisterPartnerInput], [PartnerRecord], []),
  'revokePartner' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVideoMeta' : IDL.Func([VideoMeta], [], []),
  'setChannelWasm' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'setHyveilPrincipal' : IDL.Func([IDL.Principal], [], []),
  'setMonetizationModel' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setOraclePrincipal' : IDL.Func([IDL.Principal], [], []),
  'setTokenCanisterId' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContentItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'partnerId' : IDL.Nat,
    'priceE8s' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlatformRevenue = IDL.Record({
    'partnerCount' : IDL.Nat,
    'totalCreatorShare' : IDL.Nat,
    'totalHyveilShare' : IDL.Nat,
    'totalPurchases' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const PartnerStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const PartnerRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PartnerStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'monetizationModel' : IDL.Text,
    'chains' : IDL.Vec(IDL.Text),
    'totalRevenue' : IDL.Nat,
    'registeredAt' : IDL.Int,
    'canisterId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChannelRevenue = IDL.Record({
    'partnerName' : IDL.Text,
    'creatorShare' : IDL.Nat,
    'hyveilShare' : IDL.Nat,
    'partnerId' : IDL.Nat,
    'purchaseCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'canisterId' : IDL.Principal,
  });
  const RevenueStats = IDL.Record({
    'creatorShare' : IDL.Nat,
    'hyveilShare' : IDL.Nat,
    'purchaseCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
  });
  const VideoMeta = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likes' : IDL.Nat,
    'caption' : IDL.Text,
    'blobId' : IDL.Text,
    'comments' : IDL.Vec(Comment),
    'uploadedAt' : IDL.Nat,
  });
  const ProxyResponse = IDL.Record({
    'body' : IDL.Text,
    'statusCode' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Nat,
    'contentId' : IDL.Text,
    'hyveilShareE8s' : IDL.Nat,
    'partnerId' : IDL.Nat,
    'totalAmountE8s' : IDL.Nat,
    'creatorShareE8s' : IDL.Nat,
    'timestamp' : IDL.Int,
    'buyer' : IDL.Principal,
  });
  const RegisterPartnerInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'chains' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addContentItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [ContentItem],
        [],
      ),
    'approvePartner' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimOwnerIfFirst' : IDL.Func([], [IDL.Bool], []),
    'clearChannelWasm' : IDL.Func([], [], []),
    'depositIcp' : IDL.Func([IDL.Nat], [], []),
    'getAllPartnersRevenue' : IDL.Func([], [PlatformRevenue], ['query']),
    'getApprovedPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelWasmStatus' : IDL.Func(
        [],
        [IDL.Record({ 'size' : IDL.Nat, 'loaded' : IDL.Bool })],
        ['query'],
      ),
    'getContentItems' : IDL.Func([IDL.Nat], [IDL.Vec(ContentItem)], ['query']),
    'getHyvBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getHyveilCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getHyveilPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getMyChannelsRevenue' : IDL.Func([], [IDL.Vec(ChannelRevenue)], ['query']),
    'getMyIcpBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
    'getOraclePrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getPartnerRevenue' : IDL.Func([IDL.Nat], [RevenueStats], ['query']),
    'getPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
    'getRegistrationFee' : IDL.Func([], [IDL.Nat], ['query']),
    'getTokenCanisterId' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'proxyFetch' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))),
        ],
        [ProxyResponse],
        [],
      ),
    'purchaseContent' : IDL.Func([IDL.Text], [PurchaseRecord], []),
    'registerChannelForMining' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [],
        [],
      ),
    'registerPartner' : IDL.Func([RegisterPartnerInput], [PartnerRecord], []),
    'revokePartner' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVideoMeta' : IDL.Func([VideoMeta], [], []),
    'setChannelWasm' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'setHyveilPrincipal' : IDL.Func([IDL.Principal], [], []),
    'setMonetizationModel' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setOraclePrincipal' : IDL.Func([IDL.Principal], [], []),
    'setTokenCanisterId' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };