/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PartnerStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const PartnerRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PartnerStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'chains' : IDL.Vec(IDL.Text),
  'registeredAt' : IDL.Int,
  'canisterId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProxyResponse = IDL.Record({
  'body' : IDL.Text,
  'statusCode' : IDL.Nat,
  'success' : IDL.Bool,
});
export const RegisterPartnerInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'chains' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePartner' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'depositIcp' : IDL.Func([IDL.Nat], [], []),
  'getApprovedPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyIcpBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
  'getPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
  'getRegistrationFee' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'proxyFetch' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))),
      ],
      [ProxyResponse],
      [],
    ),
  'registerPartner' : IDL.Func([RegisterPartnerInput], [PartnerRecord], []),
  'revokePartner' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PartnerStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const PartnerRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PartnerStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'chains' : IDL.Vec(IDL.Text),
    'registeredAt' : IDL.Int,
    'canisterId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProxyResponse = IDL.Record({
    'body' : IDL.Text,
    'statusCode' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const RegisterPartnerInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'chains' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePartner' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'depositIcp' : IDL.Func([IDL.Nat], [], []),
    'getApprovedPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyIcpBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
    'getPartners' : IDL.Func([], [IDL.Vec(PartnerRecord)], ['query']),
    'getRegistrationFee' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'proxyFetch' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))),
        ],
        [ProxyResponse],
        [],
      ),
    'registerPartner' : IDL.Func([RegisterPartnerInput], [PartnerRecord], []),
    'revokePartner' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };